# Generated by Django 2.2.7 on 2019-11-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_cles_identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='reponse_fille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='application_cles_identification.Question', unique=True),
        ),
    ]
