# Generated by Django 2.2.7 on 2019-11-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_cles_identification', '0002_auto_20191114_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_end',
            new_name='question_un',
        ),
    ]
